### PR TITLE
Fix a TypeError triggered in completion.js (#456)

### LINKED ISSUE #456: "TypeError: context is undefined" - qmarks, bmarks, tabgroups, history, buffers etc
Windows 10
Firefox 45.0
Vimperator 3.12.0

:qmarks
qmarks error

TypeError: context is undefined
typeerror

### PR DESCRIPTION
**Pull request by sirzerator**
Several features relying on completion lists would stop
working or not start at all when hitting this code path.

Fixes #456 as far as I can tell.

### CODE REVIEW

File: common/content/completion.js [hunk 1]
```diff
@@ -687,16 +687,17 @@ const Completion = Module("completion", {
...
+              .filter(k => k.startsWith("/list"))
+              .forEach(function(k) {
+                  let ctx = context.contexts[k];
+                  let list = template.genericOutput("",
+                      xml`<div highlight="Completions">
+                          ${ template.completionRow(ctx.title, "CompTitle") }
+                          ${ template.map2(xml, ctx.items, function (item) ctx.createRow(item), null, 100) }
+                      </div>`);
+                  commandline.echo(list, commandline.HL_NORMAL, commandline.FORCE_MULTILINE);
+              })
```
Comment (gkatsev) [inline common/content/completion.js]: can we add a semicolon here?

**Comment by gkatsev** [comment]
One comment, looks good otherwise, thanks @sirzerator.

**Comment by timss** [comment]
Thanks! Works great.
