### PR TITLE
Findbar fixes

### LINKED ISSUE #401: Findbar shows up
I am using Firefox beta 45.0b1.
With commit #371, Firefox shows the findbar in typing if the search string is not found.
By the way, one Korean character is composed of multiple inputs. So every time that I search with Korean, the findbar shows up. Furthermore, the input is broken at the moment when the findbar shows up. For example, assume that you find ```안녕```. So, you input ```ㅇ```, ```ㅏ```. Then the findbar shows up because ```아``` is not found in the page. If in this moment, you type fast, the input is broken like ```아ㄴᅟ녕```.
I tried reverting the commit. In this case, the findbar shows up only when I complete the search string and it is not found. To fix this show-up, I commented out ```window.gFindBar._findField.value = str;``` as
```
    find: Services.vc.compare(Services.appinfo.version, "25.0") >= 0 ?
    function (str) {
        let fastFind = this.fastFind;
        this._processUserPattern(str);
        let result = fastFind.find(str, this._linksOnly);
        //window.gFindBar._findField.value = str;
        this._displayFindResult(result, this._backwards);
    } :
```

### PR DESCRIPTION
**Pull request by Quicksaver**
Fixes #401:
- Don't find immediately on every key pressed while typing complex words (IME compositing).
- Don't show the findbar when searching through the command line and there are no matches.

### CODE REVIEW

**Comment by Quicksaver** [comment]
Ah hell that merge commit wasn't supposed to be in here... I'll try again.

**Comment by Quicksaver** [comment]
Hmm the pull itself doesn't actually have any other changes because of that, so it should still pull only the changes from the other commits. I'm leaving as is for now, but do let me know if you'd like me to create a cleaner pull (git is tricky sometimes...)

**Comment by gkatsev** [comment]
Thanks, I'll take a look tomorrow. Didn't get a chance to review it today.

File: common/content/commandline.js [hunk 1]
```diff
@@ -421,6 +421,16 @@ const CommandLine = Module("commandline", {
         }
     },
 
+    _isIMEComposing: false,
```
Comment (gkatsev) [inline common/content/commandline.js]: maybe this should be called something slightly more general?
While it does mostly goes to fix IME input, it could be a useful property to have and I don't think it is actually set when IME is active.

Comment (gkatsev) [inline common/content/commandline.js]: or is `compositionstart` and `compositionend` specific events for IME?

Comment (gkatsev) [inline common/content/commandline.js]: Ah, sorry, yes, this is IME specific.

File: common/content/finder.js [hunk 2]
```diff
@@ -124,15 +128,27 @@ var Finder = Module("finder", {
...
                     findBackwards: aFindPrevious
                 });
             };
+
+            // Normally the findbar appears to notify on failed results.
+            // However, this shouldn't happen when we're finding through the command line,
+            // even though that way we lose any kind of no matches notification until we
+            // stop typing altogether; something to work on at a later time:
+            // - show the quick findbar which will hide after a few seconds?
+            // - or notify the user somehow in the command line itself?
```
Comment (gkatsev) [inline common/content/finder.js]: yep, we should have the commandline turn red or something to signal this. We can either work on it as part of this PR or we can merge this one in and then work on it in another one.

File: common/content/finder.js [hunk 3]
```diff
@@ -124,15 +128,27 @@ var Finder = Module("finder", {
 
             // PDF.JS files are different, they use their own messages to communicate the results.
             // So we piggyback the end changes to the findbar when there are any.
-            findbar._original_updateControlState = findbar.updateControlState;
+            findbar._vimpbackup_updateControlState = findbar.updateControlState;
```
Comment (gkatsev) [inline common/content/finder.js]: Is this rename so that we're unlikely to tread on someone else's steps if they were doing a similar thing in another addon?

File: common/content/finder.js [hunk 4]
```diff
@@ -274,6 +290,18 @@ var Finder = Module("finder", {
             function () { finder.clear(); },
             { argCount: "0" });
     },
+    events: function() {
+        if (config.name == 'Vimperator') {
+            // Same thing as the note above for not showing the findbar on failed results
+            // through the command line, but for compatibility with FindBar Tweak.
+            events.addSessionListener(window, "WillOpenFindBar", function (event) {
```
Comment (gkatsev) [inline common/content/finder.js]: will findbar tweak respect the options above? I would prefer to keep other addon-specific fixed out of the codebase if at all possible.

**Comment by gkatsev** [comment]
Thanks! made some comments.

File: common/content/commandline.js (hunk 1 above)
Comment (Quicksaver) [inline common/content/commandline.js]: Yep. :)

File: common/content/finder.js (hunk 3 above)
Comment (Quicksaver) [inline common/content/finder.js]: Yeah, it was just a thought that occurred to me. I have seen add-ons backup ```.method``` into the same object as ```._method```, and I've also seen variants of ```.original_method``` and ```.backup_method``` as well. I thought specificity to Vimperator wouldn't hurt.

File: common/content/finder.js (hunk 2 above)
Comment (Quicksaver) [inline common/content/finder.js]: I didn't do this in this patch at least because I didn't know how to tackle it. The command line's echo methods only really show stuff when not inputting. I didn't want to create new methods/statuses/whatever because I don't really know what I'm doing there. :stuck_out_tongue_winking_eye:

File: common/content/finder.js (hunk 4 above)
Comment (Quicksaver) [inline common/content/finder.js]: FBT expects that when the original ```open``` method always leaves the findbar unhidden, which it won't because of the change above.

But I see your point, and thinking about it further it's probably better that I just add checks in FBT to see if the findbar actually opened or not after that was called. I'll upload a commit later today removing this part.

**Comment by Quicksaver** [comment]
Expect a new commit later today to remove that FBT bit as soon as I fix it on my side as well. BTW do you think just turning the commandline red on failed matches will be enough? It could reuse the style for when it shows errors and stuff, maybe.

**Comment by gkatsev** [comment]
Not positive exactly how it should look like. I'll think about it today.

**Comment by Quicksaver** [comment]
Two new commits:
- removed the FBT bits as agreed,
- addressed https://github.com/vimperator/vimperator-labs/issues/401#issuecomment-180522987 which did make for a poor UX.

**Comment by gkatsev** [comment]
LGTM. Thanks.
